modLoader="javafml"
loaderVersion="[${loader_version},)"
license="ARR"
issueTrackerURL="https://github.com/Flemmli97/FateUBW/issues"
[[mods]]
modId="fateubw"
version="${version}"
displayName="FateUBW"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fate-ubw"
logoFile="icon.png"
authors="Flemmli97"
description='''The Holy Grail War! Brought to minecraft'''
[[dependencies.fateubw]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.fateubw]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.fateubw]]
modId="tenshilib"
mandatory=true
versionRange="[1.18.2-1.6.9,)"
ordering="NONE"
side="BOTH"
