org.gradle.jvmargs=-Xmx3G
enabled_platforms=fabric,neoforge
minecraft_version=1.21.1
parchment_version=1.21:2024.07.28
# NeoForge Properties
neo_loader_version=2
neoforge_version=21.1.196
# Fabric Properties
fabric_loader_version=0.16.14

# Mod Properties
mod_version=2.0.0-beta
maven_group=io.github.flemmli97
archives_base_name=fateubw

# Dependencies
fabric_version=0.116.4+1.21.1
tenshilib_version=1.21.1-2.1.2
sbl_version=1.16.10
forge_config_api=21.1.3
modopedia=1.1.5

# Curse properties
curse_versions=1.21.1, Java 21
curse_page_fabric=https://www.curseforge.com/minecraft/mc-mods/fate-ubw-fabric
curse_id_fabric=605485
curse_dep_fabric=fabric-api, tenshilib-fabric, smartbrainlib, forge-config-api-port-fabric
optional_curse_dep_fabric=modopedia
curse_page_forge=https://www.curseforge.com/minecraft/mc-mods/fate-ubw
curse_id_forge=271719
curse_dep_forge=tenshilib, smartbrainlib
optional_curse_dep_forge=modopedia
modrinth_versions=1.21.1
modrinth_page=https://modrinth.com/mod/fate-ubw
modrinth_id=q021y7rs
modrinth_dep_fabric=fabric-api, tenshilib, smartbrainlib, forge-config-api-port
optional_modrinth_dep_fabric=modopedia
modrinth_dep_forge=tenshilib, smartbrainlib
optional_modrinth_dep_forge=modopedia

# Other
project_name=FateUBW
full_changelog=https://github.com/Flemmli97/FateUBW/blob/1.21.1/Changelog.md
discord_role=852113517108920350
