apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/arch-loom-v2/common.gradle"

repositories {
    mavenLocal()
    maven {
        name = "TenshiLib"
        url "https://maven.blazing-coop.net/releases"
    }
}

dependencies {
    modCompileOnly "io.github.flemmli97:tenshilib:${tenshilib_version}-common"
    modCompileOnly "net.tslat.smartbrainlib:SmartBrainLib-common-${minecraft_version}:${sbl_version}"
    modCompileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api}"

}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}