plugins {
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.flemmli97.multiloader.platform-neoforge'
}

neoForge {
    runs {
        var common = project(":common")
        data {
            data()
            programArguments.addAll "--all", "--mod", "fateubw"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
            programArguments.addAll "--existing", common.file("src/main/resources").absolutePath
        }
        client {
            jvmArgument "-XX:+AllowEnhancedClassRedefinition"
        }
        client2 {
            client()
            programArguments.addAll "--username", "Dev2"
        }
    }
}

ext {
    mod_meta.tenshilib_version = tenshilib_version
    mod_meta.sbl_version = sbl_version
}

repositories {
    maven {
        name = "CurseMaven"
        url "https://www.cursemaven.com"
        content {
            includeGroup 'curse.maven'
        }
    }
}

dependencies {
    implementation "io.github.flemmli97:tenshilib:${tenshilib_version}-neoforge"
    implementation "net.tslat.smartbrainlib:SmartBrainLib-neoforge-${minecraft_version}:${sbl_version}"

    implementation "net.favouriteless.modopedia:modopedia-neoforge-${minecraft_version}:${modopedia}"

    compileOnly "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"

    runtimeOnly "maven.modrinth:jade:2P7THd8J"

    //Mods useful for testing things
    runtimeOnly "io.github.flemmli97:debugutils:1.21.1-1.0.8-neoforge"
    runtimeOnly "io.github.flemmli97:mobbattle:1.21.1-2.6.2-neoforge"
    runtimeOnly "curse.maven:moonlight-499980:6682378"
    runtimeOnly "curse.maven:dummy-225738:6608246"
    runtimeOnly "curse.maven:spark-361579:6225208"
}